test tg

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -104,18 +104,18 @@ jobs:
       runs-on: ubuntu-20.04
       needs: deploy
       steps:
-      - name: curl telegram message
-        id: send
-        run: >
-          echo "::set-output name=status=$(
-          curl -L "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
-          -H "Content-Type: application/json"
-          -d "{\"chat_id\": \"-864250646\", \"text\": \"Деплой новой версии сервиса завершен успешено\!\"}")" >> $GITHUB_OUTPUT
-
-      - name: check result
-        run: |
-          if [[ ${{ steps.send.outputs.status }} != *"ok":true* ]]; then
-            echo "send is failed"
-            exit 1
-          fi
-          echo "It's OK"
+        - name: curl telegram message
+          id: tgresult
+          run: >
+            echo "::set-output name=status::$(curl -L "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
+            -H "Content-Type: application/json"
+            -d "{\"chat_id\": \"-864250646\", \"text\": \"Деплой новой версии сервиса завершен успешено\!\"}")"
+        - name: Use prior output
+          run: echo "The count was ${{ steps.tgresult.outputs.status }}"
+        - name: check result
+          run: |
+            if [[ ${{ steps.tgresult.outputs.status }} != *"ok":true* ]]; then
+              echo "send is failed"
+              exit 1
+            fi
+            echo "It's OK"
